name: Azure Pipelines

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

# ToDo: Replace the agent pool name, if you are using Udacity Cloud lab. 
# Otherwise, comment out the line below. 
pool: myAgent

variables:
  python.version: '3.9.14'
  # ToDo: Replace the service connection name as used in the DevOps project settings
  azureServiceConnectionId: 'myServiceConnection'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Environment name
  environmentName: 'test-vm'

stages:
#--------------------------------------------#  
# BUILD STAGE
#--------------------------------------------#    
- stage: Build
  jobs:
  - job: BuildInfrastructure
    pool:  myAgent
    steps:
    #--------------------------------------------#  
    # Use Terraform to create the Infrastructure      
    # Install Terraform on the pipeline agent 
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Terrafom installation'
      inputs:
        terraformVersion: '1.5.2'
    

# wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w 3a0a070f-aa82-4fcc-96c8-a410be78ce6d -s Dz13VnuFrrqqBbjUydKtj1Gi69m7ul9JTW4cc9n0GB2qX+z4SQESQq5S47onuvHRsM8W4Paw92ipBlgYyWHWQA== -d opinsights.azure.com
                # sudo apt autoremove
                # sudo apt-get upgrade -y
                # sudo apt-get update -y
                # sudo apt-get install -y xdg-utils
                # sudo apt-get remove google-chrome-stable
                # sudo rm /usr/bin/chromedriver
                # sudo rm /usr/local/bin/chromedriver
                # sudo apt-get update -y
                # sudo apt-get install python3-pip -y
                # sudo apt-get install unzip -y
                # # sudo apt-get install -y chromium-browser
                # # sudo apt-get install -y chromium-driver
                # # Install the latest version of Chrome
                # curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
                # echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
                # sudo apt-get install -y google-chrome-stable

                # # Install the latest version of ChromeDriver
                # CHROME_VERSION=$(google-chrome-stable --version | awk '{print $NF}' | cut -d '.' -f 1)
                # CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
                # wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip -O chromedriver.zip
                # unzip chromedriver.zip
                # sudo mv chromedriver /usr/local/bin/chromedriver
                # sudo chmod +x /usr/local/bin/chromedriver
                # export PATH=$PATH:/usr/local/bin/chromedriver
                # sudo apt autoremove
                # # Verify the installation
                # google-chrome-stable --version
                # chromedriver --version
                # sudo -H pip3 install --upgrade pip
                # pip install -U selenium
                # echo "python version:"
                # python3 --version 
                # export PATH=$PATH:/usr/bin/chromedriver
                # agent log analytics
            # env:  
            #   AZURE_LOG_ANALYTICS_ID: "3a0a070f-aa82-4fcc-96c8-a410be78ce6d" #$(AZURE_LOG_ANALYTICS_ID)
            #   AZURE_LOG_ANALYTICS_PRIMARY_KEY: "Dbx1jnYItRFLOcLmwIWNp3VA1OLydSFUVULzztnZasqvmMtbfolLQhyesB0/cqpCK8H/ErdjRwfVgaDtE2agbA==" #$(AZURE_LOG_ANALYTICS_PRIMARY_KEY)