name: Azure Pipelines

trigger:
- main

pool: myAgent

variables:
  python.version: '3.9.17'
  azureServiceConnectionId: 'finalProject222'
  projectRoot: $(System.DefaultWorkingDirectory)
  environmentName: 'test-vm'

stages:
- stage: Build
  jobs:
  - job: BuildInfrastructure
    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi

- stage: Deploy
  jobs:
  - deployment: FakeRestAPI
    pool: myAgent
    environment: 'test-vm'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceSettings@1
            displayName: 'Update App Service Application Settings'
            inputs:
              azureSubscription: '$(azureServiceConnectionId)'
              appName: 'finalApplication-AppService'
              appSettings: |
                [
                  {
                    "name": "WEBSITE_RUN_FROM_PACKAGE",
                    "value": "0"
                  }
                ]
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: '$(azureServiceConnectionId)'
              appType: webApp
              appName: 'finalApplication-AppService'
              package: '$(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip'
