trigger:
- main
pool: myAgent
variables:
  python.version: '3.9.17'
  # azureServiceConnectionId: 'finalProject222'
  # azureServiceConnectionId: '38800d58-310e-43a5-936f-d8024b4b1f37'
  projectRoot: $(System.DefaultWorkingDirectory)
  environmentName: 'test-vm'
  azureServiceConnectionId: '4a467d4a-01ec-4493-af5f-65413a8e5ed0'
  # Web app name
  webAppName: 'finalApplication-AppService'

stages:
- stage: Build
  jobs:
  - job: BuildInfrastructure
    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi

- stage: Deploy
  jobs:
  - deployment: FakeRestAPI
    pool: myAgent
    environment: 'test-vm'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceSettings@1
            displayName: 'Update App Service Application Settings'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              appSettings: |
                [
                  {
                    "name": "WEBSITE_RUN_FROM_PACKAGE",
                    "value": "0"
                  }
                ]
            env: {}
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appType: webApp
              webAppName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip'

